#!/usr/bin/env python3
"""
Generate CellCoal parameter files for all benchmark scenarios.

All parameter choices are documented in BENCHMARK_DESIGN.txt with
references to the CellCoal manual v1.1 and CellPhy paper (Kozlov et al. 2022).
"""

import os

# Fixed parameters (justified in BENCHMARK_DESIGN.txt)
NUM_REPLICATES = 20       # Pilot; set to 100 for full benchmark
NUM_CELLS = 40            # CellPhy Table S1: Sim 1,4,5
NUM_SITES = 10000         # CellPhy Table S1: Sim 2,3,4
EFF_POP_SIZE = 10000      # CellPhy Table S1: all simulations
GROWTH_RATE = "1e-4"      # CellPhy Table S1: all simulations
ROOT_BRANCH = 0.1         # CellPhy paper main text
OUTGROUP_BRANCH = 0.0     # CellPhy Table S1: all simulations
LINEAGE_RATE_VAR = 1.0    # CellPhy Table S1: all simulations
MUTATION_RATE = "1e-6"    # CellPhy Table S1: Sim 2,4,5,6
SITE_RATE_VAR = 1.0       # CellPhy Table S1: Sim 2

# Scenarios: (name, ADO_rate, genotype_error_mean, genotype_error_var)
# Genotype error variance must be >0 and <mean*(1-mean) per CellCoal manual Sec 6.5
# When error=0, we don't include the -G flag at all
SCENARIOS = [
    ("S1_ADO0.00_ERR0.00", 0.00, 0.00, 0.0),
    ("S2_ADO0.00_ERR0.05", 0.00, 0.05, 0.01),
    ("S3_ADO0.00_ERR0.10", 0.00, 0.10, 0.01),
    ("S4_ADO0.10_ERR0.00", 0.10, 0.00, 0.0),
    ("S5_ADO0.10_ERR0.05", 0.10, 0.05, 0.01),
    ("S6_ADO0.10_ERR0.10", 0.10, 0.10, 0.01),
    ("S7_ADO0.25_ERR0.00", 0.25, 0.00, 0.0),
    ("S8_ADO0.25_ERR0.05", 0.25, 0.05, 0.01),
    ("S9_ADO0.25_ERR0.10", 0.25, 0.10, 0.01),
]


def generate_param_file(name, ado_rate, err_mean, err_var, output_dir):
    """Generate a CellCoal parameter file for one scenario."""

    # Build ADO line: only include if ADO > 0
    if ado_rate > 0:
        ado_line = f"\t[fixed allelic dropout (ADO)] D{ado_rate}"
    else:
        ado_line = f"\t[fixed allelic dropout (ADO)] [D0.0]"

    # Build genotype error line: only include if error > 0
    # CellCoal manual Sec 6.5: -G and -C cannot be used simultaneously
    # We are NOT using -C (no reads), so -G is fine
    if err_mean > 0:
        err_line = f"\t[genotyping error; no reads] G{err_mean} {err_var}"
    else:
        err_line = f"\t[genotyping error; no reads] [G0.0 0.001]"

    results_folder = f"results_{name}"

    param_text = f"""[PARAMETER FILE for CellCoal]
[Benchmark scenario: {name}]
[Generated by generate_params.py — see BENCHMARK_DESIGN.txt for justification]

[COALESCENT]
\t[number of replicates] n{NUM_REPLICATES}
\t[number of cells] s{NUM_CELLS}
\t[number of sites] l{NUM_SITES}
\t[effective population size] e{EFF_POP_SIZE}
\t[exponential growth rate] g{GROWTH_RATE}

[GENEALOGY MODIFIERS]
\t[root branch length ratio] k{ROOT_BRANCH}
\t[outgroup branch length ratio] q{OUTGROUP_BRANCH}
\t[rate variation among branches] i{LINEAGE_RATE_VAR}

[MUTATION MODEL]
\t[alphabet binary:0 DNA:1] b1
\t[somatic mutation rate] u{MUTATION_RATE}
\t[alternative mutation model ISMhap:0 Mk2:1 finiteDNA:2] m2
\t[proportion of alternative model sites] p1
\t[base frequencies] f0.3 0.2 0.2 0.3
\t[rate variation among sites] a{SITE_RATE_VAR}
\t[mutation matrix ACGT x ACGT] r0.00 1.00 2.50 0.50
\t\t\t\t\t\t\t\t  1.00 0.00 0.50 5.00
\t\t\t\t\t\t\t\t  2.50 0.50 0.00 1.00
\t\t\t\t\t\t\t\t  0.50 5.00 1.00 0.00

[GENOTYPING PARAMETERS]
{err_line}

[scWGA PARAMETERS]
{ado_line}
\t[ADO per cell] [P0.1 0.01]
\t[ADO per site] [Q0.2 0.01]
\t[maternal allelic imbalance] [I0.5 0.01]
\t[amplification error] [A0.1 0.01 0]
\t[doublet rate per cell] [B0.1 0.01]

[NGS PARAMETERS]
\t[sequencing coverage; reads simulated] [C60]
\t[coverage overdispersion] [V5]
\t[sequencing error] [E0.01]

[OUTPUT]
\t[print SNV genotypes] 1
\t[print SNV haplotypes] 2
\t[print full genotypes] 3
\t[print full haplotypes] 4
\t[print root ancestors] [5]
\t[print trees] 6
\t[print times] [7]
\t[print CATG] [8]
\t[print PILEUP] [9]
\t[print true haplotypes] Y
\t[print consensus IUPAC sequences] x
\t[print replicates in individual folders] v
\t[results folder name] o{results_folder}

[OTHER]
\t[use tumor nomenclature for cells] W
\t[noisy] y1
"""
    filepath = os.path.join(output_dir, f"params_{name}.txt")
    with open(filepath, 'w') as f:
        f.write(param_text)
    print(f"Generated: {filepath}")
    return filepath


def main():
    output_dir = os.path.join(os.path.dirname(__file__), "params")
    os.makedirs(output_dir, exist_ok=True)

    print(f"Generating {len(SCENARIOS)} parameter files in {output_dir}/\n")
    print(f"Fixed: {NUM_CELLS} cells, {NUM_SITES} sites, "
          f"{NUM_REPLICATES} replicates, mutation rate {MUTATION_RATE}")
    print(f"Model: finite-site DNA (GTR+G), reversible\n")

    for name, ado, err_mean, err_var in SCENARIOS:
        generate_param_file(name, ado, err_mean, err_var, output_dir)

    print(f"\nDone. {len(SCENARIOS)} parameter files generated.")
    print(f"\n{'='*70}")
    print(f"HOW TO RUN:")
    print(f"{'='*70}")
    print(f"  # 1. cd into your benchmark data directory first:")
    print(f"  cd /Users/u7875558/Documents/promotion/projects/cancer_models/benchmark_simulatedData-CellCoal")
    print(f"")
    print(f"  # 2. Run CellCoal (results folders created in current directory):")
    print(f"  ~/tools/cellcoal/bin/cellcoal-1.2.0 -Fparams_S1_ADO0.00_ERR0.00.txt")
    print(f"")
    print(f"{'='*70}")
    print(f"INPUT FILES FOR EACH TOOL:")
    print(f"{'='*70}")
    print(f"  CellPhy GT16+FO+E:")
    print(f"    -> snv_hap files (IUPAC codes, 10 symbols)")
    print(f"       CellPhy handles phase ambiguity in the likelihood")
    print(f"")
    print(f"  IQ-TREE GT10+FO+G+E:")
    print(f"    -> snv_hap files (IUPAC codes, 10 symbols)")
    print(f"       Same encoding as CellPhy — use directly")
    print(f"")
    print(f"  IQ-TREE GT16+FO+G+E:")
    print(f"    -> Convert snv_gen files with convert_cellcoal_to_phylip.py")
    print(f"       IQ-TREE GT16 uses 16 distinct symbols (!, \", #, $, %, &)")
    print(f"       which differ from CellPhy's 10-symbol IUPAC encoding")
    print(f"{'='*70}")


if __name__ == '__main__':
    main()